### ISSUE TITLE
Cannot register addon

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-native-live-form#10]
I'm not sure if this lib is setup for it or not but in a generic LVN app:

```swift
import LiveViewNativeLiveForm

struct ContentView: View {
    var body: some View {
        #LiveView(
            .automatic(
                development: .localhost(path: "/"),
                production: URL(string: "https://example.com/")!
            ),
            addons: [LiveFormRegistry<_>.self]
```

adding `LiveFormRegistry<_>.self` to the `addons` list fails:

<img width="966" alt="Screenshot 2024-03-23 at 9 49 57 AM" src="https://github.com/liveview-native/liveview-native-live-form/assets/18524/8422b20b-73c8-4183-90b2-818325a43480">

**Comment by carson-katri** [comment]
That should work, but you can also write out `LiveFormRegistry<EmptyRegistry>.self` to be more explicit.

**Comment by carson-katri** [comment]
Discussion around changing this API can be found here: https://github.com/liveview-native/liveview-client-swiftui/issues/1296
