### ISSUE TITLE
Cannot compile main

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-native-live-form#15]
I'm using `main` (223deea) for the swiftui client and `main` (84e9368) for live form an getting compilation errors:

<img width="1153" alt="Screenshot 2024-06-25 at 7 14 07 AM" src="https://github.com/liveview-native/liveview-native-live-form/assets/18524/2591b028-1f0f-4c31-8825-0452f2e00f86">

I have tried clearing my package cache with no luck

**Comment by kajogo777** [comment]
I have the same issue, I can't run the app

**Comment by bcardarella** [comment]
Fixed a while bakc
