### ISSUE TITLE
Support Changesets and the `Phoenix.HTML.Form` struct.

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-native-live-form#5]
Forms in phoenix typically accept the `for` attribute and a `Phoenix.HTML.Form` struct like so:

```elixir
def render(assigns) do
  ~H"""
  <.form for={@form} phx-change="validate" phx-submit="save">
    <.input type="text" field={@form[:username]} />
    <.input type="email" field={@form[:email]} />
    <button>Save</button>
  </.form>
  """
end

def mount(_params, _session, socket) do
  {:ok, assign(socket, form: to_form(Accounts.change_user(%User{})))}
end

def handle_event("validate", %{"user" => params}, socket) do
  form =
    %User{}
    |> Accounts.change_user(params)
    |> Map.put(:action, :insert)
    |> to_form()

  {:noreply, assign(socket, form: form)}
end

def handle_event("save", %{"user" => user_params}, socket) do
  case Accounts.create_user(user_params) do
    {:ok, user} ->
      {:noreply,
       socket
       |> put_flash(:info, "user created")
       |> redirect(to: ~p"/users/#{user}")}

    {:error, %Ecto.Changeset{} = changeset} ->
      {:noreply, assign(socket, form: to_form(changeset))}
  end
end
```

Errors are stored in the changeset, which is converted into a `Phoenix.HTML.Form` struct.
These errors are automatically displayed (provided the form has been submitted).

It would be fantastic if we could support this behavior in LiveForms to make validation/error handling easier.

**Comment by carson-katri** [comment]
I think we could do this by making a SwiftUI version of the `form` and `input` function components. Then you would write something like this:

```heex
<.form for={@form} phx-change="validate" phx-submit="save">
  <.TextField field={@form[:username]} />
  <.TextField field={@form[:email]} />
  <LiveSubmitButton>Save</LiveSubmitButton>
</.form>
```

We could possibly have a separate component for all the supported form controls. I'm not sure if this is something the client should handle. Does the JS client handle this, or do these components just turn into regular HTML `<form>` elements?

**Comment by BrooklinJazz** [comment]
Phoenix's approach is to define a `.form` component, but the `.input` and `.error` components are generated into a `core_components.ex` file. I think modeling out solution after them makes sence.

We could do the same and create a `.native_form` element (or just reuse our existing LiveViewLiveForm), then generate the rest of the components.

I'm writing an article on custom components in LVN and am knowledgeable about changesets and Phoenix patterns. I can give this a shot.

**Comment by bcardarella** [comment]
Haven't we resolved this?

**Comment by BrooklinJazz** [comment]
We have. We can close the issue
