### ISSUE TITLE
Empty `TextField` sends `"null"`

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-native-live-form#6]
An empty `TextField` view in the form currently sends `"null"` value as a string.

I think this should be changed to reflect phoenix behavior and instead send an empty string `""`.

<img width="899" alt="Screenshot 2024-01-21 at 12 59 57 PM" src="https://github.com/liveview-native/liveview-native-live-form/assets/14877564/d2b02671-2b70-4c4b-9e18-5dd6778b75bc">

**Comment by bcardarella** [comment]
The LOC that is causing this is: https://github.com/liveview-native/liveview-client-swiftui/blob/d974278ed95eb6ce74f12481e8f40f11b1a60ee5/Sources/LiveViewNative/ViewModel.swift#L100-L104

The fix could be to just add a condition if `value == nil` return `""` but I defer to @carson-katri on the best implementation
